import React from "react";
import { Table } from "reactstrap";
import "../../styles/TransHistory.css";

const Transactions = props => {
  return (
    <div className="trans-wrapper">
    <div className="button-Group">
      </div >
      
      <h2>Transaction History</h2>

      <div className="table-wrapper-scroll-y my-custom-scrollbar">
        <Table
          className="trans-table"
          variant="dark"
          striped
          hover
          borderless
          responsive
        >
          <thead>
            <tr>
              <th>Date</th>
              <th>Amount</th>
              <th>Type</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>12/12/2020</td>
              <td>$25</td>
              <td>Credit</td>
              <td>Pending</td>
            </tr>
            <tr>
              <td>11/12/2019</td>
              <td>$50</td>
              <td>PayPal</td>
              <td>Complete</td>
            </tr>
            <tr>
              <td>11/10/2019</td>
              <td>$100</td>
              <td>Bitcoin</td>
              <td>Failed</td>
            </tr>
            <tr>
              <td>12/12/2020</td>
              <td>$25</td>
              <td>Credit</td>
              <td>Pending</td>
            </tr>
            <tr>
              <td>11/12/2019</td>
              <td>$50</td>
              <td>PayPal</td>
              <td>Complete</td>
            </tr>
            <tr>
              <td>11/10/2019</td>
              <td>$100</td>
              <td>Bitcoin</td>
              <td>Failed</td>
            </tr>
            <tr>
              <td>12/12/2020</td>
              <td>$25</td>
              <td>Credit</td>
              <td>Pending</td>
            </tr>
            <tr>
              <td>11/12/2019</td>
              <td>$50</td>
              <td>PayPal</td>
              <td>Complete</td>
            </tr>
            <tr>
              <td>11/10/2019</td>
              <td>$100</td>
              <td>Bitcoin</td>
              <td>Failed</td>
            </tr>
            <tr>
              <td>12/12/2020</td>
              <td>$25</td>
              <td>Credit</td>
              <td>Pending</td>
            </tr>
            <tr>
              <td>11/12/2019</td>
              <td>$50</td>
              <td>PayPal</td>
              <td>Complete</td>
            </tr>
            <tr>
              <td>11/10/2019</td>
              <td>$100</td>
              <td>Bitcoin</td>
              <td>Failed</td>
            </tr>
            <tr>
              <td>12/12/2020</td>
              <td>$25</td>
              <td>Credit</td>
              <td>Pending</td>
            </tr>
            <tr>
              <td>11/12/2019</td>
              <td>$50</td>
              <td>PayPal</td>
              <td>Complete</td>
            </tr>
            <tr>
              <td>11/10/2019</td>
              <td>$100</td>
              <td>Bitcoin</td>
              <td>Failed</td>
            </tr>
            <tr>
              <td>11/12/2019</td>
              <td>$50</td>
              <td>PayPal</td>
              <td>Complete</td>
            </tr>
            <tr>
              <td>11/10/2019</td>
              <td>$100</td>
              <td>Bitcoin</td>
              <td>Failed</td>
            </tr>
            <tr>
              <td>12/12/2020</td>
              <td>$25</td>
              <td>Credit</td>
              <td>Pending</td>
            </tr>
            <tr>
              <td>11/12/2019</td>
              <td>$50</td>
              <td>PayPal</td>
              <td>Complete</td>
            </tr>
            <tr>
              <td>11/10/2019</td>
              <td>$100</td>
              <td>Bitcoin</td>
              <td>Failed</td>
            </tr>
            <tr>
              <td>12/12/2020</td>
              <td>$25</td>
              <td>Credit</td>
              <td>Pending</td>
            </tr>
            <tr>
              <td>11/12/2019</td>
              <td>$50</td>
              <td>PayPal</td>
              <td>Complete</td>
            </tr>
            <tr>
              <td>11/10/2019</td>
              <td>$100</td>
              <td>Bitcoin</td>
              <td>Failed</td>
            </tr>
          </tbody>
        </Table>
      </div>
    </div>
  );
};

export default Transactions;
